### ISSUE TITLE
TODO Frontend

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30248-2024-EduPlanner/Frontend#17]
- [x] Comprobar que las listas de usuarios se crean (Luis)
- [x] Modals al eliminar, modificar y crear (Josemi)
- [x] Test (Ibón)
- [x] Revisión por pares
